### ISSUE TITLE
Unable to use it with Typescript

### ISSUE THREAD

**Issue by Ngomana** [gsandf/knex-expo#3]
Could not find a declaration file for module 'knex-expo'. '/node_modules/knex-expo/knex.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/knex-expo` if it exists or add a new declaration (.d.ts) file containing `declare module 'knex-expo';`

I tried running yarn add  @types/knex-expo but there are modules found.

**Comment by blakek** [comment]
Right. There aren't type definitions for this project yet.

Until then, you can start with an empty declaration file like described in [the TypeScript docs](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#your-own-definitions). You can start by adding a definition file (e.g. `knex-expo.d.ts`) and adding something like this to it:

```ts
declare module "knex-expo";
```

It's basically the equivalent of giving the whole module an `any` type.
